remote_theme: pmarsceill/just-the-docs

title: 'Decoders'
description: Elegant and battle-tested validation library for type-safe input data

# Enable site search
search_enabled: true

# When uncommented, this will be displayed instead of the title
# logo: '../img/logo@2x.png'

aux_links:
    'GitHub':
        - '//github.com/nvie/decoders'

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: 'Edit this page on GitHub'
gh_edit_repository: 'https://github.com/nvie/decoders'
gh_edit_branch: 'main'
gh_edit_source: 'docs'
gh_edit_view_mode: 'tree'
